openapi: 3.0.0
servers:
  - url: 'https://www.nsides.io/api/v1'
info:
  description: >
    The NSIDES API makes several data resources available that are useful for
    studying adverse drug reactions and drug-drug interactions. Unless otherwise
    noted, drugs are coded in RxNorm identifiers and outcomes are coded as
    SNOMED identifiers.


    The following resources are available through this API: 


    1. AEOLUS, a cleaned up version of the FDA Adverse Event Reporting System

    1. nSides,,confounding-corrected disproportionality statistics using
    multiple machine learning models

    1. SIDER, side effect data from the drug product labels

    1. GOTE, a resource of GPCRs and their targeted downstream pathways

    1. VA, a list of known and critical drug-drug interactions

    1. OMOP, access to the common vocabulary for name and concept identifier
    mapping

    1. SNOMED, vocabulary for mapping names and concept identifiers

    1. LAB, a knowledge resource that maps adverse events to common clinical
    pathology reports
  version: 1.0.0
  title: NSIDES
  termsOfService: 'http://nsides.io/terms/'
  contact:
    email: nick.tatonetti@columbia.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: translator
    x-id: 'http://ncats.nih.gov/translator/'
  - name: Adverse Drug Reaction Reporting Systems
    x-id: 'http://purl.bioontology.org/ontology/MESH/D016907'
  - name: drug
  - name: protein
  - name: pathway
paths:
  /nsides/estimateForDrug_Outcome:
    get:
      summary: ''
      description: ''
      parameters:
        - name: drugs
          in: query
          required: true
          schema:
            type: string
          description: >-
            One or more drugs to pull the top estimates for. For example use
            1309944 for amiodarone.
        - name: outcome
          in: query
          required: true
          schema:
            type: string
          description: >-
            The outcome identifier (snomed) to get the disproportionality
            estimate for. For example use 313217 for atrial fibrilation.
        - name: model
          in: query
          required: false
          schema:
            type: string
            default: dnn
            enum:
              - dnn
              - lrc
              - nopsm
          description: >-
            The model type used to estimate the statistics. Can be dnn
            (default), lrc, or nopsm.
      operationId: estimateForDrug_Outcome
      responses:
        default:
          description: Default response
  /nsides/topOutcomesForDrug:
    get:
      summary: ''
      description: ''
      parameters:
        - name: drugs
          in: query
          required: true
          schema:
            type: string
          description: >-
            One or more drugs to pull the top estimates for. For example use
            1309944 for amiodarone.
        - name: numResults
          in: query
          required: true
          schema:
            type: string
          description: Number of top outcomes to pull (e.g. 10)
        - name: model
          in: query
          required: false
          schema:
            type: string
            default: dnn
            enum:
              - dnn
              - lrc
              - nopsm
          description: >-
            The model type used to estimate the statistics. Can be dnn
            (default), lrc, or nopsm.
      operationId: topOutcomesForDrug
      responses:
        default:
          description: Default response
  /druginfo/jobIndexes:
    get:
      summary: ''
      description: ''
      parameters:
        - name: drugs
          in: query
          required: true
          schema:
            type: string
      operationId: jobIndexes
      responses:
        default:
          description: Default response
  /gote/gpcrFromUniprot:
    get:
      summary: ''
      description: ''
      parameters:
        - name: uniprot
          in: query
          required: true
          schema:
            type: string
          description: Uniprot id for the GPCR
      operationId: gpcrFromUniprot
      responses:
        default:
          description: Default response
  /lab/ae_to_lab:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: ae_to_lab
      responses:
        default:
          description: Default response
  /omop/reference:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: 'The adverse event to pull reference (e.g. case and control) data. '
      operationId: reference
      responses:
        default:
          description: Default response
  /omop/conceptsToName:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: A comma separated list of omop concept ids.
      operationId: conceptsToName
      responses:
        default:
          description: Default response
  /aeolus/ingredientList:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: ingredientList
      responses:
        default:
          description: Default response
  /aeolus/drugReactionCounts:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: The starting position (for pagination) of results to pull
      operationId: drugReactionCounts
      responses:
        default:
          description: Default response
  /aeolus/drugpairReactionCounts:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: The starting position (for pagination) of results to pull
      operationId: drugpairReactionCounts
      responses:
        default:
          description: Default response
  /aeolus/reactionListSNOMED:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: reactionListSNOMED
      responses:
        default:
          description: Default response
  /aeolus/reactionListMedDRA:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: reactionListMedDRA
      responses:
        default:
          description: Default response
  /aeolus/drugpairList:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: drugpairList
      responses:
        default:
          description: Default response
  /aeolus/drugpairReactionListMedDRA:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: drugpairReactionListMedDRA
      responses:
        default:
          description: Default response
  /snomed/getOutcomeFromSnomedId:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: Snomed outcome concept id.
      operationId: getOutcomeFromSnomedId
      responses:
        default:
          description: Default response
  /va/get_ddi_alerts:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: get_ddi_alerts
      responses:
        default:
          description: Default response
  /sider/drugForEffect:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: The umls id for the effect
      operationId: drugForEffect
      responses:
        default:
          description: Default response
  /sider/drugForEffectFreq:
    get:
      summary: ''
      description: ''
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: The umls id for the effect
      operationId: drugForEffectFreq
      responses:
        default:
          description: Default response
externalDocs:
  description: ''
  url: 'http://nsides.io'
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  securitySchemes: {}
  headers: {}
  links: {}
  callbacks: {}
security: []
